# Generated by Django 4.0.5 on 2022-08-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='myclasses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='myclasses',
            field=models.ManyToManyField(to='classes.classes'),
        ),
    ]
